import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM.
    id("org.jetbrains.kotlin.jvm").version("1.3.31")
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
    mavenCentral()
}

//deps
val awsLambdaCoreVersion = "1.2.0"
val awsLambdaEventsVersion = "2.2.6"
val javaxVersion = "3.1.0"

//test deps
val javalinVersion = "3.3.0"

dependencies {
    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    implementation("com.amazonaws:aws-lambda-java-events:$awsLambdaEventsVersion")
    implementation("com.amazonaws:aws-lambda-java-core:$awsLambdaCoreVersion")
    implementation("javax.servlet:javax.servlet-api:$javaxVersion")

    // Use the Kotlin test library.
    testImplementation("io.javalin:javalin:$javalinVersion")
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

configure<JavaPluginConvention> {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}
tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
}
