/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package se.davison.aws.lambda.apigatewayservlet

import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent
import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyResponseEvent
import io.javalin.Javalin
import org.eclipse.jetty.http.HttpMethod
import kotlin.test.Test
import kotlin.test.assertEquals

class Test {

    val app = Javalin.createStandalone()

    init {
        app.get("/") { ctx -> ctx.result("Hello World") }
        app.post("/") { ctx -> ctx.result(ctx.body()) }
        app.get("/error") { throw Exception("Error") }
    }

    private fun response(stauts: Int, body: String, contentType: String) =
            APIGatewayProxyResponseEvent()
                    .withBody(body)
                    .withStatusCode(stauts)
                    .withHeaders(mapOf("Server" to "Javalin", "Content-Type" to contentType))

    @Test
    fun testGet() {

        val proxyEvent = APIGatewayProxyRequestEvent()
                .withHttpMethod(HttpMethod.GET.asString())
                .withPath("/")
        val response = app.servlet().serve(proxyEvent)
        val expectation = response(200, "Hello World", "text/plain")

        assertEquals(expectation.toString(), response.toString())
    }

    @Test
    fun testPost() {

        val proxyEvent = APIGatewayProxyRequestEvent()
                .withHttpMethod(HttpMethod.POST.asString())
                .withBody("abc")
                .withPath("/")
        val response = app.servlet().serve(proxyEvent)
        val expectation = response(200, "abc", "text/plain")

        assertEquals(expectation.toString(), response.toString())
    }

    @Test
    fun testError() {

        val proxyEvent = APIGatewayProxyRequestEvent()
                .withHttpMethod(HttpMethod.GET.asString())
                .withPath("/error")
        val response = app.servlet().serve(proxyEvent)
        val expectation = response(500, "Internal server error", "text/plain")

        assertEquals(expectation.toString(), response.toString())
    }
}
